### ISSUE TITLE
HCC Process of Establishment

### ISSUE THREAD

**Issue by jyhi** [UICHCC/HCC-Affairs#1]
This issue is intended to keep track of the process of establishment of HCC Computer Society.

Current status (Last update: **Sun June 17, 2018**):

- [X] Reach agreement with Dr. Ricky and Ms. Kelly
- [X] Hold meetings with ITSC / IC
- [x] Submit a proposal describing our requirements to ITSC / IC
  - ~~Ongoing~~ Finished:
    - UICHCC/HCC-Regulations#7
    - UICHCC/HCC-Regulations#10
- [ ] ~~Official acknowledgement from ITSC / IC~~

**Comment by jyhi** [comment]
Update: IC does not meet our requirement:

- IC does not permit HCC to be a student society; HCC can only be an interest group under IC.
- IC requires HCC to provide _commercial support_ in cooperation with companies outside.
- IC is going to strictly limit what HCC can do in the future because of the atmosphere (as Ms. Kelly said)

Till now (June 17, 2018) HCC will continue be an online society. @UICHCC/core is going to discuss the next step HCC will take.

**Comment by billzhonggz** [comment]
TODO: discuss the possibilities of registering at SAO

**Comment by jyhi** [comment]
Update: A week ago, several Core members have had a meeting with Computer Science and Technology (CST) teachers.

HCC is now acknowledged by CST teachers and is now a semi-official _club_ under CST. So far, we can confirm that we have rights to post posters (which are audited by CST staff) and borrow classrooms (or other types of room).

One thing that needs attention is that we are still not an officially registered student interest club uner Student Affair Office (SAO). This makes HCC somehow not-very-official. With promises from teachers of CST, so far we do not have to consider it.

We can now say HCC is semi-officially established, so closing this issue.
