### ISSUE TITLE
Participation of ITSC IT & eLearning Expo 

### ISSUE THREAD

**Issue by jyhi** [UICHCC/HCC-Affairs#2]
As per discussion in WeChat we may apply for an exhibitor / speaker of the **First IT & eLearning Expo** hold by ITSC on **Tue, May 15, 2018**.

Please do share your idea below before the application deadline (there may be one, not found yet).

Note: Application form is in _UIC New Portal > Online Application System_.

**Comment by ecwu** [comment]
The most important question is what can we present if we participate in the IT & eLearning Expo.

**Comment by jyhi** [comment]
I think we could ask Dr. Ricky or Ms. Mery for ideas.

**Comment by billzhonggz** [comment]
Do it ASAP.

**Comment by jyhi** [comment]
Mail sent, waiting for response.

**Comment by jyhi** [comment]
I did not receive any response... Are there anything wrong... ?

**Comment by jyhi** [comment]
If you still have no idea then we are not going to participate this event.
